number_1 = float(input("Digite um número:"))
dn = (number_1 * 2)
tn = (number_1 * 3)
rn = (number_1 ** (1/2))
print(f"O número escolhi foi {number_1}, o dobro é {dn}, o triplo é {tn} e a raiz quadrada é {rn}")